import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { CodexExecutor } from '../src/extensions/executors/codex/codex-executor.js';
import { ROOT_RESPONSE_CONTRACT, compileRootExecutorRequest } from '../src/core/executor-contract.js';

const rootPolicy=()=>({prompt:'POLICY',skillCatalog:[],authorizedGrant:{role:'root',projectAccess:'none',networkAccess:false,inputRefs:[],sourceAccess:'none',environmentAccess:'none'}});
const subPolicy=({projectAccess='none',networkAccess=false,inputRefs=[]}={})=>({prompt:'POLICY',authorizedGrant:{role:'subagent',projectAccess,networkAccess,inputRefs,sourceAccess:inputRefs.length?'selected':'none',environmentAccess:'default'}});
class CaptureClient{constructor(){this.calls=[];}async runTurn(request){this.calls.push(request);return JSON.stringify({kind:'complete',summary:'ok',finalResult:'done',resultMode:'execution',evidence:[],claims:[],gaps:[],recommendations:[],steps:[],gateway:null,gapResolutions:[],delegations:[]});}async health(){return{available:true,connected:true,authenticated:true};}}

function runtimeRequest({taskId='T',executionId='x',projectPaths=[],grant=rootPolicy().authorizedGrant}={}){return{instructions:'compiled',context:{},responseContract:{type:'object'},authorizedGrant:grant,modelPolicy:{},runtime:{taskId,executionId,projectPaths,attachments:[]}};}

test('Codex Extension implements only the generic execute contract; role adapters stay in Core',()=>{const dir=mkdtempSync(join(tmpdir(),'taskboard-codex-generic-'));try{const executor=new CodexExecutor({runtimeRoot:join(dir,'runtime'),client:new CaptureClient()});assert.equal(typeof executor.execute,'function');assert.equal(CodexExecutor.prototype.runRoot,undefined);assert.equal(CodexExecutor.prototype.runSubagent,undefined);assert.equal(typeof executor.runRoot,'function','Core ExecutorPort may adapt internal Root calls to execute');assert.equal(typeof executor.runSubagent,'function','Core ExecutorPort may adapt internal Subagent calls to execute');assert.equal(typeof executor.runValidator,'undefined');assert.equal(typeof executor.rootPrompt,'undefined');assert.equal(typeof executor.subagentPrompt,'undefined');}finally{rmSync(dir,{recursive:true,force:true});}});

test('Codex executor health exposes Capability Provider refresh state',async()=>{const dir=mkdtempSync(join(tmpdir(),'taskboard-codex-health-')),client=new CaptureClient(),capability={execution:{available:true,connected:true,ready:true,version:'codex-fake'},provider:{requiresOpenaiAuth:true,authMode:'chatgpt'},discoveryLevel:'partial',models:[],defaults:{model:'model-a'},catalogState:'stale',lastRefresh:{ok:false,error:'timeout'}},capabilityProvider={async initialize(){return capability;},refreshState(){return{state:'manual_failed',lastRefresh:capability.lastRefresh};},snapshot(){return capability;}};try{const health=await new CodexExecutor({runtimeRoot:join(dir,'runtime'),client,capabilityProvider}).health();assert.equal(health.model,'model-a');assert.equal(health.catalogState,'stale');assert.equal(health.modelRefresh.state,'manual_failed');}finally{rmSync(dir,{recursive:true,force:true});}});

test('Core-compiled Root request exposes logical input metadata but no local source paths',async()=>{const dir=mkdtempSync(join(tmpdir(),'taskboard-codex-root-')),image=join(dir,'screen.png'),doc=join(dir,'spec.txt'),client=new CaptureClient();writeFileSync(image,Buffer.from([1,2,3]));writeFileSync(doc,'spec');try{const executor=new CodexExecutor({runtimeRoot:join(dir,'runtime'),client});await executor.runRoot({task:{id:'T',title:'分析附件',instruction:'分析',projectScopes:[],references:[],attachments:[{id:'A-1',name:'screen.png',mimeType:'image/png',size:3,path:image},{id:'A-2',name:'spec.txt',mimeType:'text/plain',size:4,path:doc}]},subagentResults:[],humanGatewayHistory:[],certifiedContext:{claims:[],gaps:[],unresolvedObligations:[]},modelPolicy:{},policyContext:rootPolicy()});const call=client.calls[0];assert.equal(call.outputSchema,ROOT_RESPONSE_CONTRACT);assert.deepEqual(call.inputItems,[]);assert.equal(call.networkAccess,false);assert.match(call.prompt,/screen\.png/);assert.match(call.prompt,/spec\.txt/);assert.doesNotMatch(call.prompt,new RegExp(image.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(call.prompt,new RegExp(doc.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));}finally{rmSync(dir,{recursive:true,force:true});}});

test('Root protocol and response schema are compiled by Core rather than Codex Extension',()=>{const request=compileRootExecutorRequest({task:{id:'T',title:'x',instruction:'goal',projectScopes:[],attachments:[],references:[],workReceipts:[]},subagentResults:[{delegationId:'WU-1',result:'fresh',evidence:[]}],humanGatewayHistory:[],policyContext:rootPolicy(),certifiedContext:{claims:[{id:'C-OLD'}],gaps:[{id:'G-1'}],unresolvedObligations:[{id:'O-2'}]}});assert.match(request.instructions,/fixed point/i);assert.match(request.instructions,/old×old, new×old, and new×new/i);assert.equal(request.responseContract,ROOT_RESPONSE_CONTRACT);assert.deepEqual(request.context.freshWorkResults.map(item=>item.delegationId),['WU-1']);assert.deepEqual(request.context.certifiedContext.claims,[{id:'C-OLD'}]);assert.equal(request.context.validatorRejection,null);});

test('Codex realizes only the compiled AuthorizedGrant and runtime paths',()=>{const dir=mkdtempSync(join(tmpdir(),'taskboard-codex-scope-')),project=join(dir,'project');mkdirSync(project);const executor=new CodexExecutor({runtimeRoot:join(dir,'runtime'),client:new CaptureClient()});try{const root=executor.executionScope(runtimeRequest({projectPaths:[],grant:rootPolicy().authorizedGrant}));assert.equal(root.projectAccess,'none');assert.equal(root.runtimeWorkspaceRoots.includes(project),false);const read=executor.executionScope(runtimeRequest({executionId:'read',projectPaths:[project],grant:subPolicy({projectAccess:'read',inputRefs:['project:0']}).authorizedGrant}));assert.equal(read.runtimeWorkspaceRoots.includes(project),true);assert.deepEqual(read.writableRoots,[]);const write=executor.executionScope(runtimeRequest({executionId:'write',projectPaths:[project],grant:subPolicy({projectAccess:'write',inputRefs:['project:0']}).authorizedGrant}));assert.equal(write.writableRoots.includes(project),true);assert.throws(()=>executor.executionScope({...runtimeRequest(),authorizedGrant:null}),/AUTHORIZED_GRANT_REQUIRED/);assert.equal(executor.cleanupTaskWorkspace('T'),true);assert.equal(existsSync(root.cwd),false);}finally{rmSync(dir,{recursive:true,force:true});}});

test('Subagent runtime facts are supplied to Core context without creating an Extension-owned protocol',async()=>{const dir=mkdtempSync(join(tmpdir(),'taskboard-codex-env-'));let probes=0;const client=new CaptureClient(),executor=new CodexExecutor({runtimeRoot:join(dir,'runtime'),client,environmentProbe:()=>{probes+=1;return{checkedAt:'now',rg:false,python:'python',pythonModules:{pdf2image:false,lxml:false},libreOffice:false,wordDesktopBinary:false};}});try{const task={id:'T',title:'附件分析',projectScopes:[],attachments:[],references:[]},delegation={id:'W',title:'W',goal:'核对',expectedOutput:'证据',stopCondition:'完成',projectAccess:'none',networkAccess:false,skillId:null,dependsOn:[],inputRefs:[]};await executor.runSubagent({task,delegation,policyContext:subPolicy(),modelPolicy:{}});await executor.runSubagent({task,delegation,policyContext:subPolicy(),modelPolicy:{}});assert.equal(probes,1);assert.match(client.calls[0].prompt,/executorRuntime/);assert.match(client.calls[0].prompt,/"rg": false/);assert.match(client.calls[0].prompt,/do not re-probe/i);assert.equal(CodexExecutor.prototype.subagentPrompt,undefined);}finally{rmSync(dir,{recursive:true,force:true});}});

test('Executor realizes AuthorizedGrant exactly or rejects unavailable capability',async()=>{const dir=mkdtempSync(join(tmpdir(),'taskboard-codex-network-')),task={id:'T',title:'network',projectScopes:[],attachments:[],references:[]},delegation={id:'W',title:'W',goal:'net',expectedOutput:'result',stopCondition:'done',projectAccess:'none',networkAccess:true,skillId:null,dependsOn:[],inputRefs:[]};try{const allowedClient=new CaptureClient(),allowed=new CodexExecutor({runtimeRoot:join(dir,'allowed'),client:allowedClient,networkAccess:true});await allowed.runSubagent({task,delegation,policyContext:subPolicy({networkAccess:true}),modelPolicy:{}});assert.equal(allowedClient.calls[0].networkAccess,true);const deniedClient=new CaptureClient(),denied=new CodexExecutor({runtimeRoot:join(dir,'denied'),client:deniedClient,networkAccess:false});await assert.rejects(denied.runSubagent({task,delegation,policyContext:subPolicy({networkAccess:true}),modelPolicy:{}}),error=>error?.runtimeUnavailable===true&&/RUNTIME_CAPABILITY_UNAVAILABLE/.test(error.message));assert.equal(deniedClient.calls.length,0);}finally{rmSync(dir,{recursive:true,force:true});}});

test('Recovery semantics are Core-compiled and Codex only transports them',async()=>{const dir=mkdtempSync(join(tmpdir(),'taskboard-codex-recovery-')),client=new CaptureClient(),executor=new CodexExecutor({runtimeRoot:join(dir,'runtime'),client});try{await executor.runRoot({task:{id:'T',title:'recover',instruction:'核对现实',projectScopes:[],attachments:[],references:[],executionState:{recovery:{effectAttempts:[{id:'effect:1',workUnitId:'WU-OLD',signature:'must-not-leak',projectAccess:'write',networkAccess:false,inputRefs:['project:0'],admittedAt:'now',reason:'effect-capable-work-admitted',resolved:false}]},retry:{scope:'effect-recovery-observe'}}},subagentResults:[],humanGatewayHistory:[],certifiedContext:{claims:[],gaps:[],unresolvedObligations:[]},modelPolicy:{},policyContext:rootPolicy()});const prompt=client.calls[0].prompt;assert.match(prompt,/RECOVERY OBSERVATION BOUNDARY/);assert.match(prompt,/effect outcome is UNKNOWN/i);assert.match(prompt,/Do not replay the old Work/i);assert.match(prompt,/Root alone may declare a mutator non-competing/i);assert.match(prompt,/effectClosures/);assert.match(prompt,/WU-OLD/);assert.doesNotMatch(prompt,/must-not-leak/);assert.ok(ROOT_RESPONSE_CONTRACT.properties.effectClosures);}finally{rmSync(dir,{recursive:true,force:true});}});
