import test from 'node:test';
import assert from 'node:assert/strict';
import { CompletionAssessmentVerifier } from '../src/governance/completion-assessment-verifier.js';
import { CompletionEvaluator, GoalState } from '../src/governance/completion-evaluator.js';

function task(){const text='检查 A、B、C 并给出完整结论';return{id:'T-1',requirementSources:[{id:'REQ-T-1-0001',text}],taskContract:{obligations:[{id:'A',certification:'supported',requirementRefs:[{sourceId:'REQ-T-1-0001',start:0,end:text.length}],criterion:{mode:'outcome',acceptedOutcomes:['succeeded']}},{id:'B',certification:'supported',requirementRefs:[{sourceId:'REQ-T-1-0001',start:0,end:text.length}],criterion:{mode:'outcome',acceptedOutcomes:['succeeded']}}]}};}

test('CompletionAssessmentVerifier certifies obligations independently and CompletionEvaluator remains the only aggregator',async()=>{const executor={async runValidator({candidates}){return{reviews:candidates.map(candidate=>({id:candidate.id,verdict:candidate.targetId==='A'?'supported':'overreach',reason:candidate.targetId==='A'?'A proven':'B missing'}))};}};const verifier=new CompletionAssessmentVerifier({executor});const result=await verifier.review({task:task(),proposal:{finalResult:'只完成 A',summary:'A done'},certifiedContext:{claims:[],gaps:[]}});assert.equal(result.assessments.length,2);assert.equal(result.assessments.find(x=>x.obligationRefs[0]==='A').certification,'supported');assert.equal(result.assessments.find(x=>x.obligationRefs[0]==='B').certification,'unresolved');const evaluated=new CompletionEvaluator().evaluate({taskContract:task().taskContract,certifiedAssessments:result.assessments});assert.equal(evaluated.goalState,GoalState.UNSATISFIED);assert.deepEqual(evaluated.unsatisfiedObligationIds,['B']);});

test('CompletionAssessmentVerifier fails closed when Validator semantic certification is unavailable',async()=>{const verifier=new CompletionAssessmentVerifier({executor:{}});const result=await verifier.review({task:task(),proposal:{finalResult:'A B C'}});assert.equal(result.assessments.every(item=>item.certification==='unresolved'),true);assert.equal(new CompletionEvaluator().evaluate({taskContract:task().taskContract,certifiedAssessments:result.assessments}).goalState,GoalState.UNSATISFIED);});
