import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';
function files(root){const out=[];if(!existsSync(root))return out;for(const name of readdirSync(root)){const p=join(root,name);if(statSync(p).isDirectory())out.push(...files(p));else out.push(p);}return out;}
test('TaskBoard repository owns only generic Extension Host surfaces',()=>{const root=resolve('src/extensions');assert.deepEqual(readdirSync(root).sort(),['index.js','ports','public-api.js','runtime']);for(const removed of ['builtins','capabilities','config','executors','surfaces'])assert.equal(existsSync(join(root,removed)),false,`${removed} belongs in TaskBoard-Ecosystem`);for(const removed of ['TaskBoard-in-Codex.vbs','docs/CODEX_INTEGRATION.md','scripts/windows-codex-desktop.mjs','scripts/windows-surface-launcher.mjs'])assert.equal(existsSync(resolve(removed)),false,`${removed} is concrete-extension material`);});
test('TaskBoard repository contains no concrete product UI',()=>{assert.equal(existsSync(resolve('src/ui')),false,'concrete product UI belongs in TaskBoard-Ecosystem');assert.equal(existsSync(resolve('src/recovery-ui/index.html')),true,'generic recovery shell must remain available when UI extensions fail');});
test('product source contains no known concrete Extension implementation',()=>{const source=files(resolve('src')).filter(p=>/\.(?:js|mjs|cjs)$/.test(p)).map(p=>readFileSync(p,'utf8')).join('\n');assert.doesNotMatch(source,/createCodexExtension|class\s+CodexExecutor|class\s+MockExecutor|OpenAI\.Codex|TASKBOARD_CODEX_/);});
test('durable product rules route every concrete Extension to Ecosystem',()=>{const constitution=readFileSync(resolve('docs/PRODUCT_CONSTITUTION.md'),'utf8'),contract=readFileSync(resolve('docs/EXTENSIONS.md'),'utf8');assert.match(constitution,/Core Repository Never Owns Concrete Extensions/);assert.match(constitution,/TaskBoard-Ecosystem/);assert.match(contract,/Repository ownership — non-negotiable/);assert.match(contract,/No TaskBoard branch may contain/);});
