import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { JsonTaskDatabase, JsonTaskRepository } from '../src/core/json-repository.js';
import { TaskStatus, ReadyReason, CompletionReason, ProjectFilter } from '../src/core/types.js';

function projection(task){return{id:task.id,title:task.title,instruction:task.instruction,status:task.status,ready_reason:task.ready_reason,completion_reason:task.completion_reason,executor_key:task.executor_key,locked:task.locked,deleted:Boolean(task.deleted_at),final_result:task.final_result,projectScopes:task.projectScopes,references:task.references.map(r=>({source_task_id:r.source_task_id,title:r.title,final_result:r.final_result})),attachments:task.attachments.map(a=>({id:a.id,name:a.name,mimeType:a.mimeType,size:a.size,path:a.path})),pendingGateway:task.pendingGateway?{status:task.pendingGateway.status,question:task.pendingGateway.question,targetGapId:task.pendingGateway.targetGapId??task.pendingGateway.target_gap_id??null,options:task.pendingGateway.options}:null,executionState:task.executionState,analysisState:task.analysisState,workReceipts:task.workReceipts,taskContract:task.taskContract,requirementSources:task.requirementSources};}

function runScenario(repo){
  let now='2026-08-01T08:00:00.000Z';repo.now=()=>now;
  const project=repo.createProject({name:'OA',path:'D:/projects/oa'}),source=repo.createTask({title:'需求基线',instruction:'分析结果',projectId:project.id,executorKey:'mock',attachments:[{id:'A-1',name:'a.txt',mimeType:'text/plain',size:3,path:'D:/attachments/a.txt',createdAt:now}]});
  now='2026-08-01T09:00:00.000Z';repo.transitionTask(source.id,TaskStatus.COMPLETED,{completionReason:CompletionReason.SUCCESS,finalResult:'immutable result'});repo.setLocked(source.id,true);
  now='2026-08-01T10:00:00.000Z';const target=repo.createTask({title:'开发任务',instruction:'基于需求开发',referenceTaskIds:[source.id],temporaryProjectPath:'D:/temp/work',executorKey:'mock'});repo.createGatewayRecord(target.id,{question:'确认范围?',context:'blocking',options:['A','B'],targetGapId:'G-SCOPE'});repo.resolveGatewayRecord(target.id,'A');
  const receipt={id:'WU-1',signature:'sig-1',workUnit:{id:'WU-1',title:'bounded',goal:'bounded',expectedOutput:'result',stopCondition:'done',projectAccess:'none',networkAccess:false,skillId:null,dependsOn:[],inputRefs:[]},result:{delegationId:'WU-1',result:'done',evidence:[],blocker:null},completed_at:now};repo.commitWorkReceipt(target.id,receipt);
  const analysisState={version:1,current:{resultMode:'analysis',evidence:[],claims:[],gaps:[],recommendations:[],steps:[]},turns:[]};repo.commitCertifiedTurn(target.id,{analysisState,workReceiptIds:['WU-1']});
  repo.setExecutionState(target.id,{retry:{scope:'root',failureCount:1,paused:false,nextAt:'2026-08-01T11:00:00.000Z'}});repo.transitionTask(target.id,TaskStatus.RUNNING,{executionState:repo.getTask(target.id).executionState});repo.transitionTask(target.id,TaskStatus.READY,{readyReason:ReadyReason.WAITING_RESOURCE,executionState:repo.getTask(target.id).executionState});
  const result={project,source:projection(repo.getTask(source.id)),target:projection(repo.getTask(target.id)),ready:repo.listTasks({status:TaskStatus.READY,title:'开发',project:ProjectFilter.UNREGISTERED}).map(projection),completed:repo.listTasks({status:TaskStatus.COMPLETED}).map(projection),phases:repo.getPhaseHistory(target.id),progress:repo.getProgressHistory(target.id),gateways:repo.listGatewayHistory(target.id).map(x=>({status:x.status,question:x.question,targetGapId:x.targetGapId??x.target_gap_id??null,answer:x.answer,options:x.options})),counts:repo.counts()};
  repo.setMaintenanceState('x',{a:1});result.maintenance=repo.getMaintenanceState('x');assert.equal(repo.hardDeleteCompletedTask(source.id),false,'locked/referenced Result must be protected');return result;
}

test('JSON repository preserves durable Task/Core facts without a parallel stage-result channel',()=>{
  const dir=mkdtempSync(join(tmpdir(),'taskboard-repo-parity-')),jsonDb=new JsonTaskDatabase(join(dir,'taskboard.json'));
  try{const result=runScenario(new JsonTaskRepository(jsonDb));assert.equal(result.target.ready_reason,ReadyReason.WAITING_RESOURCE);assert.equal(result.gateways[0].targetGapId,'G-SCOPE');assert.equal(result.maintenance.a,1);assert.equal(result.progress.length,0,'current Runtime has no progress-history writer');assert.equal(result.target.workReceipts[0].consumed_at!=null,true);assert.equal(result.target.analysisState.version,1);assert.equal('last_stage_result' in result.target,false);assert.ok(result.target.taskContract);assert.ok(result.target.requirementSources.length);}finally{jsonDb.close();rmSync(dir,{recursive:true,force:true});}
});

test('removing a Project List entry keeps existing Task scope but classifies it as unregistered',()=>{const dir=mkdtempSync(join(tmpdir(),'taskboard-project-removal-')),db=new JsonTaskDatabase(join(dir,'taskboard.json')),repo=new JsonTaskRepository(db);try{const project=repo.createProject({name:'Old OA',path:'D:/projects/old-oa'}),task=repo.createTask({title:'Existing task',instruction:'keep scope',projectId:project.id});repo.deleteProject(project.id);const hydrated=repo.getTask(task.id);assert.equal(hydrated.projectScopes.length,1);assert.equal(hydrated.projectScopes[0].source,'registry');assert.equal(hydrated.projectScopes[0].projectId,null);assert.equal(hydrated.projectScopes[0].path,'D:/projects/old-oa');assert.deepEqual(repo.listTasks({status:TaskStatus.READY,project:ProjectFilter.UNREGISTERED}).map(t=>t.id),[task.id]);}finally{db.close();rmSync(dir,{recursive:true,force:true});}});

test('WorkReceipt and Certified State are atomic durable facts; legacy progress remains read-only',()=>{const dir=mkdtempSync(join(tmpdir(),'taskboard-durable-facts-')),db=new JsonTaskDatabase(join(dir,'taskboard.json')),repo=new JsonTaskRepository(db);try{const task=repo.createTask({title:'facts',instruction:'test'}),receipt={id:'WU-1',signature:'sig',workUnit:{id:'WU-1',title:'W',goal:'W',expectedOutput:'R',stopCondition:'done',projectAccess:'none',networkAccess:false,inputRefs:[],dependsOn:[],skillId:null},result:{delegationId:'WU-1',result:'done',evidence:[],blocker:null}};repo.commitWorkReceipt(task.id,receipt);assert.equal(repo.getTask(task.id).workReceipts[0].consumed_at,null);repo.commitCertifiedTurn(task.id,{analysisState:{version:1,current:{resultMode:'analysis',evidence:[],claims:[],gaps:[],recommendations:[],steps:[]},turns:[]},workReceiptIds:['WU-1']});assert.equal(repo.getTask(task.id).analysisState.version,1);assert.ok(repo.getTask(task.id).workReceipts[0].consumed_at);assert.equal(repo.getProgressHistory(task.id).length,0);}finally{db.close();rmSync(dir,{recursive:true,force:true});}});

test('failed durable commit rolls JSON state back without a partial WorkReceipt',()=>{const dir=mkdtempSync(join(tmpdir(),'taskboard-json-rollback-')),db=new JsonTaskDatabase(join(dir,'taskboard.json')),repo=new JsonTaskRepository(db);try{const task=repo.createTask({title:'rollback',instruction:'test'}),realPersist=db.persist.bind(db);let fail=true;db.persist=()=>{if(fail)throw new Error('forced persist failure');return realPersist();};assert.throws(()=>repo.commitWorkReceipt(task.id,{id:'WU-1',signature:'sig',workUnit:{id:'WU-1'},result:{delegationId:'WU-1'}}),/forced persist failure/);fail=false;db.persist=realPersist;assert.equal(repo.getTask(task.id).workReceipts.length,0);}finally{db.close();rmSync(dir,{recursive:true,force:true});}});

test('legacy stage-result and runtime owner fields are normalized only at the Repository migration boundary',()=>{const dir=mkdtempSync(join(tmpdir(),'taskboard-runtime-migration-'));try{const file=join(dir,'legacy.json');writeFileSync(file,JSON.stringify({counters:{task:1},projects:[],phaseHistory:[],scopes:[],references:[],gateways:[],attachments:[],progressHistory:[],maintenance:{},tasks:[{id:'T-0001',title:'legacy',instruction:'x',status:'READY',ready_reason:'RESOURCE_WAIT',status_entered_at:'2026-08-01T00:00:00.000Z',created_at:'2026-08-01T00:00:00.000Z',completed_at:null,completion_reason:null,last_stage_result:'legacy stage',final_result:null,executor_key:'default',locked:false,deleted_at:null,cancel_requested_at:null,analysis_state:null,execution_state:{snapshot:{taskId:'T-0001',root:{title:'Root',status:'RUNNING',ownerType:'root',ownerLabel:'Root'},stage:{id:'s',workUnits:[{id:'w',title:'x',status:'RUNNING',ownerType:'subagent',ownerLabel:'Subagent'}]},completedWorkUnits:[]}}}]},null,2));const db=new JsonTaskDatabase(file),repo=new JsonTaskRepository(db),task=repo.getTask('T-0001');assert.equal(task.ready_reason,'WAITING_RESOURCE');assert.equal(task.executionState.snapshot.actor.owner,'root');assert.equal('root' in task.executionState.snapshot,false);assert.equal(task.executionState.snapshot.stage.workUnits[0].owner,'subagent');assert.equal('ownerType' in task.executionState.snapshot.stage.workUnits[0],false);assert.equal('last_stage_result' in task,false,'removed cognition channel is dropped during migration');db.close();}finally{rmSync(dir,{recursive:true,force:true});}});
