import { formatTaskTime as formatPhaseTime, formatWorkTiming } from './time.js';

const state={status:'READY',title:'',project:'all',projects:[],tasks:[],selectedTaskId:null,selectedGatewayOption:'',gatewayDrafts:{},taskAttachments:[],tasksRequestSeq:0,runtime:null,historyOpen:false,pendingTaskAction:null,settingLimits:{taskConcurrency:null,taskMaxSubagents:null}};
const statusCopy={READY:{title:'需执行',badge:'需执行'},RUNNING:{title:'进行中',badge:'进行中'},WAITING_HUMAN:{title:'等待你',badge:'等待你'},COMPLETED:{title:'已完成',badge:'已完成'}};
const readyReasonCopy={NEW:'新任务',HUMAN_REPLY:'你已回复',WAITING_RESOURCE:'等待资源',RETRY_WAIT:'等待重试',SUSPENDED:'有挂起项'};
const workStatusCopy={RUNNING:'执行中',COMPLETED:'已完成',WAITING_DEPENDENCY:'等待依赖',WAITING_RESOURCE:'等待资源',RETRY_WAIT:'等待重试',SUSPENDED:'挂起'};
const $=id=>document.getElementById(id);
const embedConfig=globalThis.__TASKBOARD_EMBED_CONFIG__||null;const embeddedHost=new URLSearchParams(location.search).get('host')||embedConfig?.host||null;if(embeddedHost)document.documentElement.dataset.host=embeddedHost;
const resourceUrl=path=>embedConfig?.baseUrl?new URL(path,embedConfig.baseUrl).href:path;
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function formatBytes(bytes){const size=Number(bytes||0);if(size<1024)return`${size} B`;if(size<1024*1024)return`${(size/1024).toFixed(1)} KB`;return`${(size/1024/1024).toFixed(1)} MB`;}
const MAX_ATTACHMENT_FILES=8,MAX_ATTACHMENT_FILE_BYTES=25*1024*1024,MAX_ATTACHMENT_TOTAL_BYTES=80*1024*1024;
function attachmentHint(){return'可添加文档、表格、PDF、图片、代码等；新建任务窗口内可直接 Ctrl+V 粘贴截图或复制的文件。最多 8 个，单个 25MB，总计 80MB。';}
function addTaskAttachments(incoming=[]){let added=0;for(const file of incoming){if(!(file instanceof File))continue;const duplicate=state.taskAttachments.some(x=>x.name===file.name&&x.size===file.size&&x.lastModified===file.lastModified);if(duplicate)continue;if(state.taskAttachments.length>=MAX_ATTACHMENT_FILES){toast(`最多添加 ${MAX_ATTACHMENT_FILES} 个附件`);break;}if(file.size>MAX_ATTACHMENT_FILE_BYTES){toast(`${file.name} 超过单个 25MB 限制`);continue;}const total=state.taskAttachments.reduce((s,x)=>s+x.size,0);if(total+file.size>MAX_ATTACHMENT_TOTAL_BYTES){toast('附件总大小不能超过 80MB');break;}state.taskAttachments.push(file);added++;}renderAttachmentSelection();return added;}
function clipboardImageFile(file,index=0){const type=file.type||'image/png';const ext=({'image/png':'png','image/jpeg':'jpg','image/webp':'webp','image/gif':'gif'})[type]||'png';const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\..+$/,'').replace('T','-');return new File([file],`截图-${stamp}${index?`-${index+1}`:''}.${ext}`,{type,lastModified:Date.now()});}
function renderAttachmentSelection(){const box=$('attachment-selection');if(!state.taskAttachments.length){box.innerHTML=`<span class="hint-inline">${attachmentHint()}</span>`;return;}box.innerHTML=state.taskAttachments.map((file,index)=>`<div class="attachment-row"><div class="attachment-row-main"><span class="attachment-row-name">${escapeHtml(file.name)}</span><span class="attachment-row-meta">${escapeHtml(file.type||'文件')} · ${formatBytes(file.size)}</span></div><button type="button" class="attachment-remove" data-remove-attachment="${index}">移除</button></div>`).join('');document.querySelectorAll('[data-remove-attachment]').forEach(btn=>btn.addEventListener('click',()=>{state.taskAttachments.splice(Number(btn.dataset.removeAttachment),1);renderAttachmentSelection();}));}
function resetTaskAttachments(){state.taskAttachments=[];$('task-attachments').value='';renderAttachmentSelection();}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2400);}

const errorCopy={TITLE_REQUIRED:'请填写任务标题',INSTRUCTION_REQUIRED:'请填写任务内容',PROJECT_FIELDS_REQUIRED:'请填写项目名称和路径',PROJECT_OR_TEMP_ONLY:'已有项目和临时项目范围只能选择一个',PROJECT_NOT_FOUND:'选择的项目不存在，请刷新后重试',PROJECT_NAME_EXISTS:'项目名称已经存在',PROJECT_PATH_EXISTS:'这个项目路径已经登记',PROJECT_PATH_NOT_FOUND:'项目路径不存在，请检查后重试',PROJECT_PATH_NOT_DIRECTORY:'项目路径必须是一个文件夹',REFERENCE_MUST_BE_COMPLETED:'只能引用仍保留的已完成任务',ANSWER_REQUIRED:'请补充必要信息',NO_PENDING_GATEWAY:'这个任务当前已经不在等待你的输入',ATTACHMENT_TOO_MANY:'附件数量超过限制',ATTACHMENT_TOO_LARGE:'有附件超过单个 25MB 限制',ATTACHMENT_TOTAL_TOO_LARGE:'附件总大小超过 80MB 限制',ATTACHMENT_INVALID:'附件格式无法处理，请重新添加',REQUEST_TOO_LARGE:'本次上传内容过大',TASK_CANCEL_NOT_ALLOWED:'任务当前状态已经变化，无法执行取消。请刷新后按当前状态操作。',TASK_DELETE_BECAME_RUNNING:'任务刚刚已经开始执行，当前无法删除。如需停止，请使用「取消任务」。',TASK_DELETE_NOT_ALLOWED:'当前状态不能删除任务。',TASK_LOCKED:'任务已锁定，无法删除。请先解除锁定。',TASK_LOCK_NOT_ALLOWED:'只有已完成任务可以锁定。',TASK_RETRY_NOT_ALLOWED:'当前任务没有可手动重试的挂起项。',RETRY_TARGET_NOT_SUSPENDED:'这个工作项当前已经不是挂起状态。',TASK_NOT_QUIESCENT:'任务仍在收尾，请稍后再试。'};
function readableError(error){const m=error?.message||String(error||'操作失败');return errorCopy[m]||m;}
function reportError(error){console.error(error);toast(readableError(error));}
async function withPending(button,action){if(button?.disabled)return;if(button){button.disabled=true;button.setAttribute('aria-busy','true');}try{return await action();}finally{if(button){button.disabled=false;button.removeAttribute('aria-busy');}}}
function api(path,options={}){if(embedConfig?.rpc&&typeof globalThis.__taskboardEmbeddedRequest==='function')return globalThis.__taskboardEmbeddedRequest(path,options);return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open(options.method||'GET',path,true);const body=options.body??null;const isForm=typeof FormData!=='undefined'&&body instanceof FormData;const headers={...(options.headers||{})};if((options.method||'GET').toUpperCase()!=='GET'&&!Object.keys(headers).some(k=>k.toLowerCase()==='x-taskboard-action'))headers['x-taskboard-action']='ui';if(!isForm&&body!=null&&!Object.keys(headers).some(k=>k.toLowerCase()==='content-type'))headers['content-type']='application/json';for(const[k,v]of Object.entries(headers))xhr.setRequestHeader(k,v);xhr.onreadystatechange=()=>{if(xhr.readyState!==XMLHttpRequest.DONE)return;let payload={};try{payload=xhr.responseText?JSON.parse(xhr.responseText):{};}catch{return reject(new Error(`服务器返回了无法解析的响应 (${xhr.status||0})`));}if(xhr.status>=200&&xhr.status<300)resolve(payload);else reject(new Error(payload.error||`请求失败 (${xhr.status||0})`));};xhr.onerror=()=>reject(new Error('无法连接 TaskBoard 服务'));xhr.ontimeout=()=>reject(new Error('TaskBoard 请求超时'));xhr.timeout=options.timeout||120000;xhr.send(body);});}

async function refreshDashboard(){const d=await api('/api/dashboard');state.projects=d.projects;$('count-ready').textContent=d.counts.READY;$('count-running').textContent=d.counts.RUNNING;$('count-waiting').textContent=d.counts.WAITING_HUMAN;$('count-completed').textContent=d.counts.COMPLETED;renderProjectEnums();}
function renderProjectEnums(){const taskProject=$('task-project');const draftProjectId=taskProject?.value||'';$('project-mini-list').innerHTML=state.projects.slice(0,7).map(p=>`<div class="project-mini" title="${escapeHtml(p.path)}">${escapeHtml(p.name)}</div>`).join('')||'<div class="project-mini">暂无项目</div>';$('project-filter').innerHTML=`<option value="all">全部项目</option>${state.projects.map(p=>`<option value="${p.id}">${escapeHtml(p.name)}</option>`).join('')}<option value="unregistered">未登记项目</option>`;$('project-filter').value=state.project;taskProject.innerHTML=`<option value="">不关联</option>${state.projects.map(p=>`<option value="${p.id}">${escapeHtml(p.name)}</option>`).join('')}`;if(draftProjectId&&state.projects.some(p=>p.id===draftProjectId))taskProject.value=draftProjectId;$('project-list').innerHTML=state.projects.map(p=>`<div class="project-row"><div><b>${escapeHtml(p.name)}</b><span>${escapeHtml(p.path)}</span></div><button class="delete-button" data-delete-project="${p.id}">移除</button></div>`).join('')||'<div class="hint">还没有登记项目。临时项目范围不需要登记。</div>';document.querySelectorAll('[data-delete-project]').forEach(btn=>btn.addEventListener('click',async()=>{try{await withPending(btn,async()=>{await api(`/api/projects/${btn.dataset.deleteProject}`,{method:'DELETE'});await refreshDashboard();await refreshTasks();});}catch(e){reportError(e);}}));}

async function refreshTasks({preserveSelection=true}={}){const seq=++state.tasksRequestSeq;if(preserveSelection&&state.selectedTaskId){try{const current=await api(`/api/tasks/${encodeURIComponent(state.selectedTaskId)}`);if(seq!==state.tasksRequestSeq)return;if(current.task?.status&&current.task.status!==state.status){state.status=current.task.status;state.title='';state.project='all';$('title-search').value='';$('project-filter').value='all';$('page-title').textContent=statusCopy[state.status].title;document.querySelectorAll('.status-item').forEach(btn=>btn.classList.toggle('is-active',btn.dataset.status===state.status));}}catch(error){if(error?.message==='TASK_NOT_FOUND')state.selectedTaskId=null;else console.warn('[selected-task]',error);}}
  const qs=new URLSearchParams({status:state.status,title:state.title,project:state.project});const body=await api(`/api/tasks?${qs}`);if(seq!==state.tasksRequestSeq)return;state.tasks=body.tasks;if(!preserveSelection||!state.tasks.some(t=>t.id===state.selectedTaskId))state.selectedTaskId=state.tasks[0]?.id||null;renderTasks();renderDetail();refreshRuntime();}
function projectLabel(task){const registered=task.projectScopes.filter(s=>s.source==='registry'&&s.projectId).map(s=>s.label);if(registered.length)return registered.join(' + ');return'未登记项目';}
function completionPresentation(task){if(task?.status!=='COMPLETED')return{badge:statusCopy[task?.status]?.badge||'',resultTitle:'',tone:''};if(task.completion_reason==='SUCCESS')return{badge:'已完成',resultTitle:'最终结果',tone:'success'};if(task.completion_reason==='CANCELLED')return{badge:'已取消',resultTitle:'任务结果 · 已取消',tone:'cancelled'};return{badge:'已结束',resultTitle:'任务结果 · 完成原因未确认',tone:'unresolved'};}
function displayTaskBadge(task){return completionPresentation(task).badge;}
function taskCardTimes(task){const phase=`<span class="phase-inline">${displayTaskBadge(task)} · ${formatPhaseTime(task.status_entered_at)}</span>`;if(task.status!=='COMPLETED')return phase;return`<span class="task-time-stack"><span class="created-inline">创建 · ${formatPhaseTime(task.created_at)}</span>${phase}</span>`;}
function renderTasks(){$('result-count').textContent=`${state.tasks.length} 个结果`;$('empty-state').classList.toggle('hidden',state.tasks.length>0);$('task-list').innerHTML=state.tasks.map(task=>{const view=completionPresentation(task);return`<button class="task-card ${task.id===state.selectedTaskId?'is-selected':''}" data-task-id="${task.id}"><div class="task-card-top"><div class="task-title-stack">${task.status==='READY'?`<span class="ready-reason ${escapeHtml(task.ready_reason||'NEW')}">${readyReasonCopy[task.ready_reason]||'需执行'}</span>`:''}<div class="task-title">${task.locked?'🔒 ':''}${escapeHtml(task.title)}</div></div><span class="mini-badge ${task.status} ${view.tone}">${view.badge}</span></div><div class="task-snippet">${escapeHtml(task.instruction)}</div><div class="task-card-bottom"><span class="project-chip">${escapeHtml(projectLabel(task))}${task.attachments?.length?` · 📎${task.attachments.length}`:''}</span>${taskCardTimes(task)}</div></button>`;}).join('');document.querySelectorAll('[data-task-id]').forEach(card=>card.addEventListener('click',()=>{state.selectedTaskId=card.dataset.taskId;state.runtime=null;state.historyOpen=false;renderTasks();renderDetail();refreshRuntime();}));}

function selectedTask(){return state.tasks.find(t=>t.id===state.selectedTaskId)||null;}
function renderDetail(){const task=selectedTask();$('detail-empty').classList.toggle('hidden',Boolean(task));$('detail-content').classList.toggle('hidden',!task);if(!task)return;const view=completionPresentation(task);$('detail-id').textContent=task.id;$('detail-title').textContent=task.title;$('detail-status').textContent=view.badge;$('detail-status').className=`phase-badge ${task.status} ${view.tone}`;$('detail-phase-time').textContent=`${view.badge} · ${formatPhaseTime(task.status_entered_at)}`;$('detail-instruction').textContent=task.instruction;$('detail-project').textContent=task.projectScopes.length?task.projectScopes.map(s=>`${s.label} · ${s.path}`).join('\n'):'未登记项目';$('detail-reference').textContent=task.references.length?task.references.map(r=>`${r.source_task_id} · ${r.title}`).join('\n'):'无';
  const attachments=task.attachments||[];$('detail-attachment-section').classList.toggle('hidden',attachments.length===0);$('detail-attachments').innerHTML=attachments.map(a=>`<a class="detail-attachment" href="${escapeHtml(resourceUrl(`/api/tasks/${encodeURIComponent(task.id)}/attachments/${encodeURIComponent(a.id)}`))}" target="_blank" rel="noopener"><span class="detail-attachment-icon">📎</span><span class="detail-attachment-main"><span class="detail-attachment-name">${escapeHtml(a.name)}</span><span class="detail-attachment-meta">${escapeHtml(a.mimeType||'文件')} · ${formatBytes(a.size)}</span></span></a>`).join('');
  const gateway=task.pendingGateway;$('gateway-card').classList.toggle('hidden',!gateway);if(gateway){state.selectedGatewayOption='';$('gateway-question').textContent=gateway.question;$('gateway-context').textContent=gateway.context||'';$('gateway-answer').value=state.gatewayDrafts[gateway.id]||'';$('gateway-options').innerHTML=(gateway.options||[]).map(option=>`<button type="button" class="gateway-option ${state.gatewayDrafts[gateway.id]===option?'is-selected':''}" data-option="${escapeHtml(option)}">${escapeHtml(option)}</button>`).join('');document.querySelectorAll('[data-option]').forEach(btn=>btn.addEventListener('click',()=>{state.selectedGatewayOption=btn.dataset.option;state.gatewayDrafts[gateway.id]=state.selectedGatewayOption;$('gateway-answer').value=state.selectedGatewayOption;document.querySelectorAll('[data-option]').forEach(x=>x.classList.toggle('is-selected',x===btn));}));$('gateway-answer').oninput=e=>{state.gatewayDrafts[gateway.id]=e.target.value;};}
  $('result-card').classList.toggle('hidden',task.status!=='COMPLETED');$('result-title').textContent=view.resultTitle;$('final-result').textContent=task.final_result||'';renderTaskActions(task);renderRuntime();}

function renderTaskActions(task){const lock=$('task-lock-button'),action=$('task-action-button');lock.classList.toggle('hidden',task.status!=='COMPLETED');if(task.status==='COMPLETED'){lock.textContent=task.locked?'🔒':'🔓';lock.title=task.locked?'已锁定：点击解除锁定':'未锁定：点击锁定长期保留';}let mode=null;if(task.status==='RUNNING'||task.status==='WAITING_HUMAN')mode='cancel';else if(task.status==='READY'||task.status==='COMPLETED')mode='delete';action.classList.toggle('hidden',!mode);action.dataset.mode=mode||'';action.textContent=mode==='cancel'?'取消任务':'删除任务';action.disabled=mode==='delete'&&task.status==='COMPLETED'&&task.locked;action.title=action.disabled?'已锁定，无法删除。请先解除锁定。':'';}

function runtimeWork(runtime){const current=runtime?.current||{};const stageUnits=current.stage?.workUnits||[];const active=stageUnits.filter(unit=>unit.status!=='COMPLETED');const seen=new Set();const completed=[];for(const unit of [...(current.completedWorkUnits||[]),...stageUnits.filter(unit=>unit.status==='COMPLETED')]){const key=`${unit.stageId||current.stage?.id||'stage'}:${unit.id||unit.title||''}`;if(seen.has(key))continue;seen.add(key);completed.push(unit);}const currentActor=current.actor;const actor=currentActor&&['RUNNING','WAITING_RESOURCE','RETRY_WAIT'].includes(currentActor.status)?[currentActor]:[];return{actor,active,completed,workUnits:[...active,...completed]};}
function workOwnerLabel(unit){if(unit?.owner==='root')return'Root';if(unit?.owner==='validator')return'Validator';if(unit?.owner==='subagent')return'Subagent';return unit?.status==='WAITING_RESOURCE'||unit?.status==='WAITING_DEPENDENCY'?'未分配':'';}
function workCapabilityLabel(unit){if(unit?.owner!=='subagent')return'';const project=unit?.projectAccess==='write'?'可写':unit?.projectAccess==='read'?'只读':'无';return`项目访问：${project} · 网络：${unit?.networkAccess===true?'允许':'关闭'}`;}
function summarizeWork(units){if(!units.length)return'';const counts={};for(const u of units)counts[u.status]=(counts[u.status]||0)+1;const pieces=[];for(const key of ['RUNNING','COMPLETED','WAITING_DEPENDENCY','WAITING_RESOURCE','RETRY_WAIT','SUSPENDED'])if(counts[key])pieces.push(`${counts[key]} 项${workStatusCopy[key]}`);return`当前阶段 ${units.length} 项工作 · ${pieces.join(' · ')}`;}
function renderWorkCard(u){const owner=workOwnerLabel(u),capabilities=workCapabilityLabel(u),timing=formatWorkTiming(u);return`<article class="work-card ${String(u.status||'').toLowerCase()}"><div class="work-card-head"><div class="work-heading"><div class="work-title">${escapeHtml(u.title||'当前工作')}</div>${owner?`<div class="work-owner">${escapeHtml(owner)}</div>`:''}${capabilities?`<div class="work-capabilities">${escapeHtml(capabilities)}</div>`:''}</div><div class="work-status-wrap"><span class="work-status ${u.status}">${workStatusCopy[u.status]||u.status||''}</span>${u.status==='SUSPENDED'?`<button type="button" class="retry-icon" data-retry-work="${escapeHtml(u.id||'root')}" title="重新尝试" aria-label="重新尝试">↻</button>`:''}</div></div><div class="work-detail">${escapeHtml(u.detail||'').replace(/\n/g,'<br>')}</div>${timing?`<div class="work-time">${escapeHtml(timing)}</div>`:''}</article>`;}
function renderWorkGroup(label,items){return items.length?`<div class="runtime-work-group"><div class="runtime-work-group-label">${escapeHtml(label)}</div>${items.map(renderWorkCard).join('')}</div>`:'';}
function renderRuntime(){const task=selectedTask();if(!task)return;const completionView=completionPresentation(task);const runtime=state.runtime&&state.runtime.taskId===task.id?state.runtime:null;const fallback=task.status==='READY'?{taskId:task.id,state:task.ready_reason==='SUSPENDED'?'suspended':'queued',summary:task.ready_reason==='SUSPENDED'?'任务存在挂起项':task.ready_reason==='RETRY_WAIT'?'等待自动重试':task.ready_reason==='WAITING_RESOURCE'?'等待执行资源':'等待执行',detail:task.ready_reason==='SUSPENDED'?'自动恢复已停止，请按正文指引重试。':task.ready_reason==='RETRY_WAIT'?'上一轮执行未成功；系统会在错峰等待后自动重试。':task.ready_reason==='WAITING_RESOURCE'?'当前没有可用执行资源；资源恢复后自动继续。':'Scheduler 会在满足条件后自动开始。',updatedAt:task.status_entered_at,current:task.executionState?.snapshot||null,history:[]}:task.status==='RUNNING'?{taskId:task.id,state:'running',summary:'正在执行',detail:'Root 已接管本轮执行。',updatedAt:task.status_entered_at,current:null,history:[]}:task.status==='WAITING_HUMAN'?{taskId:task.id,state:'waiting',summary:'等待你的必要信息',detail:'当前任务已静止。',updatedAt:task.status_entered_at,current:task.executionState?.snapshot||null,history:[]}:{taskId:task.id,state:'completed',summary:completionView.tone==='success'?'任务已完成':completionView.tone==='cancelled'?'任务已取消':'任务已结束，完成原因未确认',detail:'',updatedAt:task.status_entered_at,current:null,history:[]};const value=runtime||fallback;const work=runtimeWork(value);$('runtime-overview').textContent=work.workUnits.length?(summarizeWork(work.workUnits)||value.summary||''):(work.actor.length?(value.summary||'正在判断'):'');$('runtime-time').textContent=formatPhaseTime(value.updatedAt||task.status_entered_at);
  const notice=$('resource-notice');const showNotice=!work.workUnits.length&&!work.actor.length&&value.detail;notice.classList.toggle('hidden',!showNotice);notice.textContent=showNotice?value.detail:'';
  const list=$('runtime-work-list');if(work.workUnits.length||work.actor.length){list.innerHTML=[renderWorkGroup('正在判断',work.actor),renderWorkGroup('当前工作',work.active),renderWorkGroup('已完成工作',work.completed)].join('');document.querySelectorAll('[data-retry-work]').forEach(btn=>btn.addEventListener('click',()=>retryWork(btn)));}else{list.innerHTML=`<article class="work-card single"><div class="work-card-head"><div class="work-title">${escapeHtml(value.summary||'当前状态')}</div><span class="work-status simple">${displayTaskBadge(task)}</span></div><div class="work-detail">${escapeHtml(value.detail||'').replace(/\n/g,'<br>')}</div></article>`;}
  renderHistory(value.history||[]);
}
function renderHistory(history){const body=$('history-progress');$('history-toggle-text').textContent=state.historyOpen?'收起 ▴':'展开 ▾';body.classList.toggle('hidden',!state.historyOpen);body.innerHTML=history.length?history.map(item=>`<div class="history-node"><span class="history-dot"></span><div><b>${escapeHtml(item.title)}</b><p>${escapeHtml(item.detail||'')}</p><time>${formatPhaseTime(item.completed_at)}</time></div></div>`).join(''):'<div class="history-empty">当前还没有已确认结论。</div>';}
async function retryWork(button){const task=selectedTask();if(!task)return;try{await withPending(button,async()=>{await api(`/api/tasks/${encodeURIComponent(task.id)}/retry`,{method:'POST',body:JSON.stringify({workUnitId:button.dataset.retryWork})});toast('已重新进入尝试流程，将从第 1/5 次开始');await refreshDashboard();await refreshTasks();await refreshRuntime();});}catch(e){reportError(e);}}
async function refreshRuntime(){const taskId=state.selectedTaskId;if(!taskId){state.runtime=null;return;}try{const body=await api(`/api/tasks/${encodeURIComponent(taskId)}/runtime`,{timeout:15000});if(state.selectedTaskId!==taskId)return;state.runtime=body.runtime||null;renderRuntime();}catch(error){if(error?.message!=='TASK_NOT_FOUND')console.warn('[runtime]',error);}}

function executorConnectionLabel(h){
  const name=h.displayName||h.executor||'Executor';
  if(h.preparing)return`${name} · 正在准备执行组件，无需操作`;
  if(!h.available)return`${name} · 执行组件未就绪，请检查网络或本机 ${name}`;
  if(h.connected===false)return`${name} · 暂时不可用，将自动重试`;
  if(h.authenticated===false)return`${name} · 尚未登录，请先在 ${name} 中完成登录`;
  if(h.ready===false)return`${name} · 配置未就绪，请在 ${name} 中检查`;
  if(h.executor==='mock')return`${name} · 已连接`;
  if(h.authMode==='chatgpt')return`${name} · 已连接${h.planType?` · ChatGPT ${String(h.planType).replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}`:' · ChatGPT'}`;
  if(String(h.authMode||'').toLowerCase()==='apikey')return`${name} · 已连接 · OpenAI API`;
  if(h.providerId&&String(h.providerId).toLowerCase()!=='openai')return`${name} · 已连接 · ${h.providerId}`;
  return`${name} · 已连接`;
}
function executorModelLabel(h={}){if(h.model)return`AI 模型 · ${h.model}${h.catalogState==='fresh'?'':' · 能力待刷新'}`;return'AI 模型 · Executor 默认（兜底）';}
function executorRefreshPresentation(h={}){const refresh=h.modelRefresh||null,last=refresh?refresh.lastRefresh:(h.lastModelRefresh||null),state=refresh?.state||'idle';if(state==='refreshing')return{state:'refreshing',busy:true,title:`正在${refresh?.source==='manual'?'手动':'自动'}刷新 AI 模型信息…`};if(state==='success'||(!refresh&&last?.ok===true))return{state:'success',busy:false,title:`最近刷新成功${last?.at?` · ${last.at}`:''}${h.model?` · ${h.model}`:''}`};if(state==='manual_failed'||(!refresh&&last?.ok===false&&last?.source==='manual'))return{state:'manual-failed',busy:false,title:`手动刷新失败，已保留当前模型记录${last?.error?` · ${last.error}`:''}`};if(state==='startup_failed'||(!refresh&&last?.ok===false))return{state:'startup-failed',busy:false,title:`首次自动刷新失败，已保留当前模型记录${last?.error?` · ${last.error}`:''}`};return{state:'idle',busy:false,title:'刷新 AI 模型信息'};}
function applyExecutorRefreshPresentation(h={}){const button=$('executor-model-refresh'),view=executorRefreshPresentation(h);button.dataset.refreshState=view.state;button.setAttribute('aria-busy',view.busy?'true':'false');button.disabled=Boolean(view.busy);button.title=view.title;button.setAttribute('aria-label',view.title);}
async function checkExecutor(){try{const body=await api('/api/health');const h=body.executor||{};const ready=h.ready??Boolean(h.available&&h.connected!==false&&h.authenticated!==false);$('executor-strip').classList.toggle('busy',Boolean(h.preparing));$('executor-strip').classList.toggle('ok',ready&&!h.preparing);$('executor-strip').classList.toggle('bad',!ready&&!h.preparing);$('executor-text').textContent=executorConnectionLabel(h);$('executor-model-text').textContent=executorModelLabel(h);const details=[h.version,h.error].filter(Boolean);$('executor-text').title=details.join(' · ');$('executor-model-text').title=h.model||(h.catalogState==='unavailable'?'未取得明确模型，当前使用 Executor 默认配置':'当前模型记录未改变');applyExecutorRefreshPresentation(h);}catch{$('executor-strip').classList.remove('ok','busy');$('executor-strip').classList.add('bad');$('executor-text').textContent='Executor · 不可用';$('executor-model-text').textContent='AI 模型 · Executor 默认（兜底）';applyExecutorRefreshPresentation({});}}
async function refreshExecutorModel(){const button=$('executor-model-refresh');if(button.disabled)return;try{button.disabled=true;button.dataset.refreshState='refreshing';button.setAttribute('aria-busy','true');button.title='正在手动刷新 AI 模型信息…';const body=await api('/api/capabilities/refresh',{method:'POST',body:'{}',timeout:15000});await checkExecutor();if(body.refreshed)toast('AI 模型信息已刷新');else toast(`刷新失败，已保留当前模型${body.error?`：${body.error}`:''}`);}catch(error){await checkExecutor();toast(`刷新失败，已保留当前模型：${readableError(error)}`);}finally{if(button.dataset.refreshState==='refreshing'){button.disabled=false;button.setAttribute('aria-busy','false');}}}
$('executor-model-refresh').addEventListener('click',refreshExecutorModel);
function setStatus(status){state.status=status;state.title='';state.project='all';state.selectedTaskId=null;state.runtime=null;state.historyOpen=false;$('title-search').value='';$('project-filter').value='all';$('page-title').textContent=statusCopy[status].title;document.querySelectorAll('.status-item').forEach(btn=>btn.classList.toggle('is-active',btn.dataset.status===status));return refreshTasks({preserveSelection:false}).catch(reportError);}

document.querySelectorAll('.status-item').forEach(btn=>btn.addEventListener('click',()=>setStatus(btn.dataset.status)));let searchTimer=null;$('title-search').addEventListener('input',e=>{state.title=e.target.value;clearTimeout(searchTimer);searchTimer=setTimeout(()=>refreshTasks().catch(reportError),160);});$('project-filter').addEventListener('change',e=>{state.project=e.target.value;refreshTasks().catch(reportError);});
function openNewTask(){ $('task-form').reset();resetTaskAttachments();$('reference-task-id').value='';$('reference-chip').classList.add('hidden');$('task-dialog').showModal(); }
$('new-task-button').addEventListener('click',openNewTask);$('task-dialog-close').addEventListener('click',()=>$('task-dialog').close());$('task-dialog-cancel').addEventListener('click',()=>$('task-dialog').close());
$('create-task-submit').addEventListener('click',async()=>{const button=$('create-task-submit'),title=$('task-title').value.trim(),instruction=$('task-instruction').value.trim();if(!title||!instruction)return toast('请填写任务标题和任务内容');if($('task-project').value&&$('task-temp-project-path').value.trim())return toast('已有项目和临时项目范围二选一');const referenceId=$('reference-task-id').value;try{await withPending(button,async()=>{const form=new FormData();form.append('title',title);form.append('instruction',instruction);if($('task-project').value)form.append('projectId',$('task-project').value);if($('task-temp-project-path').value.trim())form.append('temporaryProjectPath',$('task-temp-project-path').value.trim());if(referenceId)form.append('referenceTaskIds',referenceId);state.taskAttachments.forEach(file=>form.append('attachments',file,file.name));const body=await api('/api/tasks',{method:'POST',body:form});$('task-dialog').close();state.status='READY';state.project='all';state.title='';state.selectedTaskId=body.task.id;$('page-title').textContent='需执行';document.querySelectorAll('.status-item').forEach(btn=>btn.classList.toggle('is-active',btn.dataset.status==='READY'));await refreshDashboard();await refreshTasks();toast('任务已创建，已进入需执行');});}catch(e){reportError(e);}});
$('attachment-pick-button').addEventListener('click',()=>$('task-attachments').click());$('task-attachments').addEventListener('change',e=>{addTaskAttachments([...(e.target.files||[])]);e.target.value='';});$('task-dialog').addEventListener('paste',e=>{const c=e.clipboardData;if(!c)return;const itemFiles=[...(c.items||[])].filter(i=>i.kind==='file').map(i=>i.getAsFile()).filter(Boolean);const raw=itemFiles.length?itemFiles:[...(c.files||[])];if(!raw.length)return;const normalized=raw.map((file,index)=>{const generic=!file.name||/^(image|blob|pasted[-_ ]?image)(?:\.[a-z0-9]+)?$/i.test(file.name);return file.type?.startsWith('image/')&&generic?clipboardImageFile(file,index):file;});e.preventDefault();const added=addTaskAttachments(normalized);if(added)toast(`已粘贴 ${added} 个附件`);});

$('gateway-submit').addEventListener('click',async()=>{const answer=$('gateway-answer').value.trim();if(!answer)return toast('请补充必要信息');const button=$('gateway-submit');try{await withPending(button,async()=>{const current=selectedTask();if(current?.pendingGateway?.id)delete state.gatewayDrafts[current.pendingGateway.id];await api(`/api/tasks/${state.selectedTaskId}/human-gateway`,{method:'POST',body:JSON.stringify({answer})});await refreshDashboard();await setStatus('READY');toast('已收到，任务已回到需执行');});}catch(e){reportError(e);}});
$('reference-task-button').addEventListener('click',()=>{const task=selectedTask();if(!task)return;$('task-form').reset();resetTaskAttachments();$('reference-task-id').value=task.id;$('reference-chip').textContent=`引用 ${task.id} · ${task.title}`;$('reference-chip').classList.remove('hidden');$('task-title').value=`基于「${task.title}」继续`;$('task-dialog').showModal();});

$('task-lock-button').addEventListener('click',async()=>{const task=selectedTask();if(!task||task.status!=='COMPLETED')return;const button=$('task-lock-button');try{await withPending(button,async()=>{await api(`/api/tasks/${task.id}/lock`,{method:'POST',body:JSON.stringify({locked:!task.locked})});toast(task.locked?'已解除锁定':'已锁定，任务不会被删除或自动清理');await refreshTasks();});}catch(e){reportError(e);}});
function openTaskAction(){const task=selectedTask();if(!task)return;const mode=$('task-action-button').dataset.mode;if(!mode)return;state.pendingTaskAction={taskId:task.id,mode};if(mode==='cancel'){$('task-action-title').textContent='取消这个任务？';$('task-action-description').textContent=task.status==='WAITING_HUMAN'?'Scheduler 会重新确认任务当前是否静止；如已存在执行，会先让 Root 收尾。取消完成后，任务会进入「已完成」并标记为「已取消」。':'Scheduler 会要求 Root 停止后续工作分配并收尾当前执行。Root 确认静止后，任务会进入「已完成」并标记为「已取消」。';$('task-action-confirm').textContent='取消任务';}else{$('task-action-title').textContent='删除这个任务？';$('task-action-description').textContent=task.status==='COMPLETED'?'任务会从页面隐藏，底层使用逻辑删除。已锁定任务不能删除。':'任务将不会执行，并从页面隐藏，底层使用逻辑删除。';$('task-action-confirm').textContent='删除任务';}$('task-action-dialog').showModal();}
$('task-action-button').addEventListener('click',openTaskAction);$('task-action-close').addEventListener('click',()=>$('task-action-dialog').close());$('task-action-back').addEventListener('click',()=>$('task-action-dialog').close());$('task-action-confirm').addEventListener('click',async()=>{const action=state.pendingTaskAction;if(!action)return;const button=$('task-action-confirm');try{await withPending(button,async()=>{if(action.mode==='cancel'){const body=await api(`/api/tasks/${action.taskId}/cancel`,{method:'POST',body:JSON.stringify({})});$('task-action-dialog').close();toast(body.pending?'正在取消：Root 完成收尾后会自动进入已完成':'任务已取消');}else{await api(`/api/tasks/${action.taskId}`,{method:'DELETE',body:JSON.stringify({})});$('task-action-dialog').close();state.selectedTaskId=null;toast('任务已删除，页面不再显示');}await refreshDashboard();await refreshTasks();});}catch(e){reportError(e);}});

$('history-toggle').addEventListener('click',()=>{state.historyOpen=!state.historyOpen;renderRuntime();});
$('add-project-link').addEventListener('click',()=>$('project-dialog').showModal());$('project-dialog-close').addEventListener('click',()=>$('project-dialog').close());
function renderSettingLimits(body={}){if(body.limits)state.settingLimits={...state.settingLimits,...body.limits};const settings=body.settings||{taskConcurrency:Number($('setting-task-concurrency').value),taskMaxSubagents:Number($('setting-task-max-subagents').value)},limits=state.settingLimits||{};const taskWarning=$('setting-task-limit-warning'),subagentWarning=$('setting-subagent-limit-warning'),note=$('setting-capability-note');const taskLimit=Number(limits.taskConcurrency),subagentLimit=Number(limits.taskMaxSubagents);const taskConfigured=Number(settings.taskConcurrency),subagentConfigured=Number(settings.taskMaxSubagents);if(Number.isInteger(taskLimit)&&taskLimit>0&&taskConfigured>taskLimit){taskWarning.textContent=`当前 AI 上限为 ${taskLimit}，实际最多执行 ${taskLimit} 个任务`;taskWarning.classList.remove('hidden');}else{taskWarning.textContent='';taskWarning.classList.add('hidden');}if(Number.isInteger(subagentLimit)&&subagentLimit>0&&subagentConfigured>subagentLimit){subagentWarning.textContent=`当前 AI 上限为 ${subagentLimit}，每个 Task 实际最多同时执行 ${subagentLimit} 个 Subagent`;subagentWarning.classList.remove('hidden');}else{subagentWarning.textContent='';subagentWarning.classList.add('hidden');}const known=(Number.isInteger(taskLimit)&&taskLimit>0)||(Number.isInteger(subagentLimit)&&subagentLimit>0);if(known){note.textContent='';note.classList.add('hidden');}else{note.textContent='AI 并发能力：未报告明确上限，当前按配置尽可能执行。';note.classList.remove('hidden');}}
async function openSimpleSettings(){try{const body=await api('/api/settings');const settings=body.settings||{};$('setting-task-concurrency').value=String(settings.taskConcurrency||2);$('setting-task-max-subagents').value=String(settings.taskMaxSubagents||3);renderSettingLimits(body);$('settings-dialog').showModal();}catch(e){reportError(e);}}
$('setting-task-concurrency').addEventListener('change',()=>renderSettingLimits());$('setting-task-max-subagents').addEventListener('change',()=>renderSettingLimits());$('simple-config-link').addEventListener('click',openSimpleSettings);$('settings-dialog-close').addEventListener('click',()=>$('settings-dialog').close());$('settings-dialog-cancel').addEventListener('click',()=>$('settings-dialog').close());$('settings-save').addEventListener('click',async()=>{const button=$('settings-save');try{await withPending(button,async()=>{const body=await api('/api/settings',{method:'PUT',body:JSON.stringify({taskConcurrency:Number($('setting-task-concurrency').value),taskMaxSubagents:Number($('setting-task-max-subagents').value)})});renderSettingLimits(body);$('settings-dialog').close();toast('简易配置已保存');});}catch(e){reportError(e);}});$('project-add').addEventListener('click',async()=>{const name=$('project-name').value.trim(),path=$('project-path').value.trim();if(!name||!path)return toast('请填写项目名称和路径');const button=$('project-add');try{await withPending(button,async()=>{await api('/api/projects',{method:'POST',body:JSON.stringify({name,path})});$('project-name').value='';$('project-path').value='';await refreshDashboard();toast('已加入项目列表');});}catch(e){reportError(e);}});
$('exit-taskboard')?.addEventListener('click',async()=>{if(!confirm('退出 TaskBoard？正在运行的本地服务会停止。'))return;try{await api('/api/system/shutdown',{method:'POST',headers:{'x-taskboard-action':'shutdown'},body:JSON.stringify({})});document.body.innerHTML='<div style="min-height:100vh;display:grid;place-items:center;font-family:Segoe UI,Microsoft YaHei,sans-serif;color:#555;background:#f5f6f8"><div style="text-align:center"><h2 style="margin:0 0 8px;color:#222">TaskBoard 已退出</h2><p style="margin:0">可以直接关闭这个浏览器页面。</p></div></div>';}catch(e){reportError(e);}});

try{await refreshDashboard();await refreshTasks({preserveSelection:false});await checkExecutor();globalThis.__TASKBOARD_APP_READY__=true;if(embeddedHost&&window.parent&&window.parent!==window){window.parent.postMessage({type:'taskboard:ready',host:embeddedHost},'*');}}catch(error){globalThis.__TASKBOARD_APP_READY__=false;reportError(error);}setInterval(()=>{refreshDashboard().then(()=>refreshTasks()).catch(error=>console.warn('[refresh]',error));},4000);setInterval(()=>checkExecutor().catch(error=>console.warn('[executor]',error)),15000);setInterval(()=>refreshRuntime().catch(error=>console.warn('[runtime-refresh]',error)),2000);
