const $=id=>document.getElementById(id);
let state={extensions:[],activeUiId:null,discoveryErrors:{}};
function api(path,options={}){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open(options.method||'GET',path,true);if((options.method||'GET').toUpperCase()!=='GET')xhr.setRequestHeader('x-taskboard-action','ui');if(options.body!=null)xhr.setRequestHeader('content-type','application/json');xhr.onreadystatechange=()=>{if(xhr.readyState!==XMLHttpRequest.DONE)return;let body={};try{body=xhr.responseText?JSON.parse(xhr.responseText):{};}catch{return reject(new Error(`无法解析响应 (${xhr.status||0})`));}if(xhr.status>=200&&xhr.status<300)resolve(body);else reject(new Error(body.error||`请求失败 (${xhr.status||0})`));};xhr.onerror=()=>reject(new Error('无法连接 TaskBoard 服务'));xhr.send(options.body??null);});}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function toast(message){const node=$('toast');node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2600);}
function status(item){return item.status==='loaded'?'已加载':item.status==='load-failed'?`加载失败 · ${item.error||''}`:'等待重启';}
function render(){
  const errors=Object.entries(state.discoveryErrors||{});const errorBox=$('discovery-errors');errorBox.classList.toggle('hidden',errors.length===0);errorBox.textContent=errors.map(([path,error])=>`${path}\n${error}`).join('\n\n');
  const box=$('extensions');if(!state.extensions.length){box.innerHTML='<div class="muted">没有发现扩展。把扩展放到 data/extensions/&lt;id&gt;，或在下方手动导入。</div>';return;}
  box.innerHTML=state.extensions.map(item=>{const tags=[item.provides?.executor?'Executor':null,item.provides?.continuation?'Continuation':null,item.provides?.ui?'UI':null,item.source==='system'?'系统目录':'手动导入'].filter(Boolean);const active=item.id===state.activeUiId;const action=item.provides?.ui?`<button data-ui="${escapeHtml(item.id)}" ${item.status!=='loaded'||active?'disabled':''}>${active?'当前 UI':'设为 UI'}</button>`:'';return`<div class="item"><div class="item-main"><div class="item-title">${escapeHtml(item.displayName)}</div><div class="item-meta">${escapeHtml(item.directory)} · ${escapeHtml(status(item))}</div><div class="tags">${tags.map(tag=>`<span class="tag ${active&&tag==='UI'?'active':''}">${escapeHtml(tag)}</span>`).join('')}</div></div>${action}</div>`;}).join('');
  document.querySelectorAll('[data-ui]').forEach(button=>button.addEventListener('click',()=>selectUi(button.dataset.ui)));
}
async function load(){try{state=await api('/api/extensions');render();}catch(error){toast(error.message);}}
async function selectUi(id){try{const body=await api('/api/extensions/active-ui',{method:'PUT',body:JSON.stringify({id})});state=body.registry||state;render();toast('UI 已选择；重启 TaskBoard 后生效');}catch(error){toast(error.message);}}
async function importExtension(){const directory=String($('directory').value||'').trim();if(!directory)return toast('请填写扩展目录');const button=$('import');button.disabled=true;try{const body=await api('/api/extensions/import',{method:'POST',body:JSON.stringify({directory})});state=body.registry||state;$('directory').value='';render();toast('扩展已导入；重启后加载');}catch(error){toast(error.message);}finally{button.disabled=false;}}
$('refresh').addEventListener('click',load);$('import').addEventListener('click',importExtension);load();
