const SAFE_REASONING_RANK=Object.freeze({low:0,medium:1,high:2});
function reasoningBand(value){const raw=String(value||'').trim().toLowerCase();if(['tiny','minimal','low'].includes(raw))return'low';if(['balanced','medium'].includes(raw))return'medium';if(['deep','high'].includes(raw))return'high';return null;}
function chooseMinimumSufficientEffort(efforts,targetBand){const targetRank=SAFE_REASONING_RANK[targetBand];if(!Number.isInteger(targetRank))return null;return(Array.isArray(efforts)?efforts:[]).map(item=>({value:item?.value||null,band:reasoningBand(item?.value)})).filter(item=>item.value&&item.band&&SAFE_REASONING_RANK[item.band]>=targetRank).sort((a,b)=>SAFE_REASONING_RANK[a.band]-SAFE_REASONING_RANK[b.band])[0]?.value||null;}
function taskComplexity(task){const instruction=String(task?.instruction||''),title=String(task?.title||''),attachments=Array.isArray(task?.attachments)?task.attachments.length:0,scopes=Array.isArray(task?.projectScopes)?task.projectScopes.length:0,references=Array.isArray(task?.references)?task.references.length:0;let score=0;if(title.length+instruction.length>240)score+=1;if(title.length+instruction.length>700)score+=1;if(attachments)score+=1;if(scopes)score+=1;if(references)score+=1;if(/架构|重构|迁移|安全|并发|性能|复杂|综合|全量|完整|端到端|root cause|architecture|migration|security|performance/i.test(`${title} ${instruction}`))score+=1;return score;}
function isRetrievalAnalysis(task){const value=`${task?.title||''}\n${task?.instruction||''}`,hasSourceContext=(Array.isArray(task?.attachments)&&task.attachments.length>0)||(Array.isArray(task?.projectScopes)&&task.projectScopes.length>0),asksAnalysis=/分析|核对|审查|根据附件|根据项目|需求|查找|定位|review|analy[sz]e|inspect/i.test(value),asksDeepDesign=/架构设计|重构|迁移|安全审计|性能优化|并发设计|端到端重构|architecture design|migration|security audit/i.test(value);return hasSourceContext&&asksAnalysis&&!asksDeepDesign;}
function configuredModel(snapshot){const value=String(snapshot?.defaults?.model||'').trim();return value||null;}
function supportsExplicitModelSelection(snapshot){const selection=snapshot?.modelSelection;return selection?.explicitPerTurn===true&&Number.isInteger(selection?.maxPerTurn)&&selection.maxPerTurn>=1;}
function taskContext(task){const cwd=(task?.projectScopes||[]).map(scope=>scope?.path).find(Boolean)||null;return cwd?{cwd}:null;}
function workText(work){return[work?.title,work?.goal,work?.expectedOutput,work?.stopCondition].map(value=>String(value||'').trim()).filter(Boolean).join('\n');}
function isFiniteReadOnlyWork(work){return Boolean(work&&String(work?.projectAccess||'none').toLowerCase()==='read'&&String(work?.goal||'').trim()&&String(work?.expectedOutput||'').trim()&&String(work?.stopCondition||'').trim());}
function isBroadProjectWork(work){const refs=Array.isArray(work?.inputRefs)?work.inputRefs.map(value=>String(value||'').trim()).filter(Boolean):[];if(!refs.some(ref=>ref.startsWith('project:')))return false;return/审计|全链路|关键链路|全量|全仓|整个项目|跨实现|跨配置|跨运行时|跨验证|跨模块|跨文件|audit\b|repository[- ]wide|cross[- ](?:module|file|runtime|implementation)/i.test(workText(work));}
function isDeepWork(value){return/架构|重构|迁移|安全审计|性能优化|并发设计|根因|全量|端到端|复杂|architecture|refactor|migration|security audit|performance optimization|root cause|end[- ]to[- ]end|complex/i.test(String(value||''));}
function requiredModelTier(role,task,work){if(role==='subagent'){const local=workText(work);return isFiniteReadOnlyWork(work)&&!isDeepWork(local)&&!isBroadProjectWork(work)?'efficient':'balanced';}const value=`${task?.title||''}\n${task?.instruction||''}`;return taskComplexity(task)>=4||isDeepWork(value)?'frontier':'balanced';}
function requiredReasoningBand(role,task,work){if(role==='subagent')return isFiniteReadOnlyWork(work)&&!isDeepWork(workText(work))&&!isBroadProjectWork(work)?'low':'medium';if(isRetrievalAnalysis(task))return'medium';const value=`${task?.title||''}\n${task?.instruction||''}`;return taskComplexity(task)>=4||isDeepWork(value)?'high':'medium';}
function modelMetadataText(model){let specialty='';try{specialty=typeof model?.modelSpecialty==='string'?model.modelSpecialty:JSON.stringify(model?.modelSpecialty||'');}catch{specialty='';}return`${model?.displayName||''}\n${model?.description||''}\n${specialty}`.toLowerCase();}
function inferredModelTier(model){const value=modelMetadataText(model);if(/frontier|flagship|strongest capability|hardest|most complex|complex reasoning|deep reasoning|advanced reasoning|long[- ]running|research|agentic|highest quality|maximum quality|difficult tasks/.test(value))return'frontier';if(/balanced|general[- ]purpose|general purpose|everyday|daily work|all[- ]around|all around|reliable default|default choice|standard coding|versatile/.test(value))return'balanced';if(/fast|efficient|affordable|low[- ]latency|low latency|high[- ]throughput|high throughput|routine|repetitive|straightforward|lightweight|cost[- ]effective|cost effective/.test(value))return'efficient';return null;}
function priorityValue(model){const value=Number(model?.priority);return Number.isFinite(value)?value:Number.MAX_SAFE_INTEGER;}
function chooseModelForTier(models,requiredTier,configured){const available=(Array.isArray(models)?models:[]).filter(model=>model?.id&&!model.hidden),tiered=available.map(model=>({model,tier:inferredModelTier(model)})).filter(item=>item.tier),acceptable=requiredTier==='efficient'?['efficient','balanced','frontier']:requiredTier==='balanced'?['balanced','frontier']:['frontier'];for(const tier of acceptable){const matches=tiered.filter(item=>item.tier===tier).map(item=>item.model).sort((a,b)=>{const configuredDelta=(a.id===configured?0:1)-(b.id===configured?0:1);return configuredDelta||priorityValue(a)-priorityValue(b)||String(a.id).localeCompare(String(b.id));});if(matches.length)return{model:matches[0],tier};}return null;}

export class ModelRouter{
  constructor({capabilityProvider=null}={}){this.capabilityProvider=capabilityProvider;this.prepared=new Map();}
  release(taskId){if(taskId)this.prepared.delete(taskId);}
  async prepare({task}={}){if(!this.capabilityProvider?.discover)return null;let snapshot=null;try{snapshot=await this.capabilityProvider.discover({context:taskContext(task)});}catch{snapshot=this.capabilityProvider.snapshot?.()||null;}if(task?.id)this.prepared.set(task.id,snapshot);return snapshot;}
  route({role,task,work=null}){
    if(!['root','subagent'].includes(role)){const error=new Error(`MODEL_ROUTE_ROLE_INVALID:${String(role||'missing')}`);error.nonRetryable=true;throw error;}
    const snapshot=(task?.id&&this.prepared.get(task.id))||this.capabilityProvider?.snapshot?.()||null,configured=configuredModel(snapshot),requiredTier=requiredModelTier(role,task,work),policy={quality:requiredTier==='frontier'?'quality':'balanced',model:null,configuredDefaultModel:configured,reasoningEffort:null,capabilityLevel:snapshot?.discoveryLevel||'basic',routeReason:'executor-default'};
    if(snapshot?.routingSafe===false||!supportsExplicitModelSelection(snapshot))return policy;
    if(configured){policy.model=configured;policy.routeReason='configured-model';}
    const selection=chooseModelForTier(snapshot?.models,requiredTier,configured),selectedModel=selection?.model||(snapshot?.models||[]).find(model=>model.id===configured)||null;if(!selectedModel)return policy;policy.model=selectedModel.id;
    const efforts=Array.isArray(selectedModel.reasoningEfforts)?selectedModel.reasoningEfforts:[],targetBand=requiredReasoningBand(role,task,work),chosen=chooseMinimumSufficientEffort(efforts,targetBand);if(chosen)policy.reasoningEffort=chosen;
    if(selection){policy.routeReason=`minimum-sufficient-model-${requiredTier}`;return policy;}if(!efforts.length)return{...policy,routeReason:'known-model-default-effort'};
    return{...policy,routeReason:chosen?(isRetrievalAnalysis(task)?'minimum-sufficient-retrieval':`minimum-sufficient-${targetBand}`):'known-model-default-effort'};
  }
}
